server.port=8083
spring.application.name=order-service

spring.datasource.url=jdbc:postgresql://localhost:5432/product-managementDB
spring.datasource.username=postgres
spring.datasource.password=7483
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

user.service.url=http://localhost:8081/api/users
product.service.url=http://localhost:8082/api/products

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
